### ISSUE TITLE
I'm banned too

### ISSUE THREAD

**Issue by ghost** [VSabertail/STOP-HATE-GUYS#2]
I'm banned by a dick named LegitSoulja. He was my friend but then I asked him for help on this project and he started banning me and I said "fuck you." Then got banned from OgarUL. Even the owner of it was excited and I decided to make my own private server implementation. Fuck Andrews, Fuck LegitSoulja, Fuck everyone in OgarUL.

**Comment by AlexandriteErikParacelsus** [comment]
@XtremePlayzCODE Haha your situation has gone worse and you said "F you" that's why LegitSoulja banned you.

**Comment by ghost** [comment]
I said it after he banned me.

**Comment by VSabertail** [comment]
i got banned for saying I LOVE DIEP.io twice

**Comment by ghost** [comment]
Noice
